[config]
schemaVersion = "1.0.0"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Citroos"
name = "Dr_Pepper_Cure_All"
description = "Replaces the Cure-All with Dr. Pepper."
websiteUrl = "https://github.com/citroos/DrPepperCureAll"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"
PEAKModding-PEAKLib_Core = "1.7.0"
PEAKModding-PEAKLib_Items = "1.6.0"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/DrPepperCureAll/release/DrPepperCureAll.dll"
target = "plugins/DrPepperCureAll/DrPepperCureAll.dll"

[[build.copy]]
source = "drpepper.peakbundle"
target = "plugins/DrPepperCureAll/drpepper.peakbundle"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "peak", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/peak/category/
peak = [ "mods", "all", "items", ]
